### ISSUE TITLE
[Feature] Add flags to the badges

### ISSUE THREAD

**Issue by TaxMachine** [mezotv/discord-badges#11]
Example
1 is Discord staff
2 is Discord Partner
4 is Hypesquad event
8 is Bug Hunter
64 is Bravery
128 is Brillance
256 is Balance
512 is Early Supporter
16384 is Gold Bug Hunter
131072 is Early Verified Bot Developper
4194304 is Active Developper
4587584 is Moderator Programs Alumni

**Comment by mezotv** [comment]
Hey @TaxMachine 
Thanks for that bug what exactly are the flags for?

**Comment by mezotv** [comment]
> Maybe bit index or 2^x would be more readable

Probably yea I'm still not sure when I'll add this as I don't got the flag id for every badge and couldn't find all of them on the docs page

**Comment by oceaann** [comment]
> > Maybe bit index or 2^x would be more readable
> 
> Probably yea I'm still not sure when I'll add this as I don't got the flag id for every badge and couldn't find all of them on the docs page

`/users/:ID` endpoint can help I think

**Comment by mezotv** [comment]
> `/users/:ID` endpoint can help I think

I believe that the endpoint returns all the flags combined in one number

**Comment by oceaann** [comment]
> I believe that the endpoint returns all the flags combined in one number

It's a binary when every bit is an individual flag. You can eliminate all you know and find the right bit.

**Comment by mezotv** [comment]
This has been resolved in #12 @TaxMachine @oceaann
