### ISSUE TITLE
Needed verified bot badge.

### ISSUE THREAD

**Issue by DarkFalc0n** [mezotv/discord-badges#14]
The verified bot badge is missing from this collection.
![image](https://github.com/mezotv/discord-badges/assets/59203815/f750ef27-0a94-4d4f-9cd1-134ea49e6664)

**Comment by mezotv** [comment]
I would count that as a badge would you?

**Comment by DarkFalc0n** [comment]
Well I was creating a discord user presence widget and I saw that the user that the discord api returned had the verified bot listed as a badge ('flag' in the api doc). I created a map that matched the values to urls of badges from your collection and the widget works really well for all types of users except bots, well because I couldn't actually find the bot badge file on the internet. Also as the url prefix is the same for all the other badges, I had to include a few lines of extra code and add an url exception for the bot flag/badge. It is fine though if you dont consider the bot label as a badge.

**Comment by mezotv** [comment]
> Well I was creating a discord user presence widget and I saw that the user that the discord api returned had the verified bot listed as a badge ('flag' in the api doc, 2^16). I created a map that matched the values to urls of badges from your collection and the widget works really well for all types of users except bots, well because I couldn't actually find the bot badge file on the internet. Also as the url prefix is the same for all the other badges, I had to include a few lines of extra code and add an url exception for the bot flag/badge. It is fine though if you dont consider the bot label as a badge.

Perhaps I could add an extra section for special "flags" like the AI or verified bot flag

**Comment by DarkFalc0n** [comment]
> > Well I was creating a discord user presence widget and I saw that the user that the discord api returned had the verified bot listed as a badge ('flag' in the api doc, 2^16). I created a map that matched the values to urls of badges from your collection and the widget works really well for all types of users except bots, well because I couldn't actually find the bot badge file on the internet. Also as the url prefix is the same for all the other badges, I had to include a few lines of extra code and add an url exception for the bot flag/badge. It is fine though if you dont consider the bot label as a badge.
> 
> Perhaps I could add an extra section for special "flags" like the AI or verified bot flag

Okay, that would be helpful and also reduce the different origin dependency from my app.

**Comment by mezotv** [comment]
Hey @DarkFalc0n quick update on this. I was gonna add it but sadly cant find any resources with a high quality svg file for those badges. If you know some that be appreciated!

**Comment by DarkFalc0n** [comment]
@mezotv I searched as well but got no leads, so far, atleast. I will let you know if I find anything in the future.

**Comment by mezotv** [comment]
> @mezotv I searched as well but got no leads, so far, atleast. I will let you know if I find anything in the future.
> 

I will probably just remake them myself once I got home probably gonna take around 1-2hours i'll let you know once they are added!

**Comment by DarkFalc0n** [comment]
@mezotv okay, sounds good.

**Comment by mezotv** [comment]
> @mezotv okay, sounds good.

Alright, I have tried my best to add them all they arent perfect but it's pretty close. I hope this works well enough for your use case!

**Comment by DarkFalc0n** [comment]
@mezotv thanks! the badge looks perfect
