### ISSUE TITLE
some flags arent here

### ISSUE THREAD

**Issue by Mrgaton** [mezotv/discord-badges#18]
the flags arent here

TEAM_PSEUDO_USER (2 ^ 10) and  BOT_HTTP_INTERACTIONS (2 ^19)

**Comment by mezotv** [comment]
Hey @Mrgaton,

It doesn't seem like these flags belong to any badge, whats up with those?

**Comment by Mrgaton** [comment]
From the discord [DEVELOPER PORTAL](https://discord.com/developers/applications) 

![image](https://github.com/mezotv/discord-badges/assets/68958481/db4eb83c-b79e-49e5-9ab7-7c0611f24804)

there are some flags that aren't here

**Comment by mezotv** [comment]
> From the discord [DEVELOPER PORTAL](https://discord.com/developers/docs/resources/user) 
> 
> ![image](https://github.com/mezotv/discord-badges/assets/68958481/db4eb83c-b79e-49e5-9ab7-7c0611f24804)
> 
> there are some flags that aren't here

Those flags have nothing to do with the repository.
