### ISSUE TITLE
Add png version of the badges

### ISSUE THREAD

**Issue by Mrgaton** [mezotv/discord-badges#19]

**Comment by mezotv** [comment]
I don't think this is needed as you can convert the svgs to png easily.

**Comment by Mrgaton** [comment]
but i want to use the repository as the API for my web :C

**Comment by mezotv** [comment]
> but i want to use the repository as the API for my web :C

Modern websites should use svg or atleast webp files anyways so I dont think this is a valid reason.

**Comment by mezotv** [comment]
> yes but i want to use it on a program where his framework doesn't support svg

What framework is that?
