### ISSUE TITLE
Server Owner Crown

### ISSUE THREAD

**Issue by Braandn** [mezotv/discord-badges#23]
Wrong Text in the "Earned by" Field:

"Given to servers that have community features enabled and have atleast 1 boost."

Regardless of having the community features enabled and having a 1 boost or not, this Crown is only given to the Server Owner if there is no Role with hoist and administrator permission.

**Comment by mezotv** [comment]
Ohh yea good catch, I actually forgot to add the description when I copied over the format from the previous badge

**Comment by mezotv** [comment]
Fixed this in the most recent comit!
