### ISSUE TITLE
Add staff server badge

### ISSUE THREAD

**Issue by Denis0014** [mezotv/discord-badges#27]
How about adding a staff server badge?
Of course, I am not an employee of discord, but I think that officially only employees can get this server icon

![image](https://github.com/mezotv/discord-badges/assets/109104246/4eea36cd-f093-4e82-bfc4-cafdd74cde4f)

Title: Internal Employee (Staff)
https://github.com/mezotv/discord-badges/assets/109104246/0b594f86-efe5-40ab-9427-d0855f29bd42

**Comment by mezotv** [comment]
I could add that yea, do you still have the discord cdn link where that badge is from and some proof that its actually a thing?

**Comment by Denis0014** [comment]
I used a snippet from this repository:
https://github.com/neme-sys-io/DiscordGuild-StaffMode
You can check the code and apply it on your **client**, it's absolutely safe

**Comment by mezotv** [comment]
Oh yea seems legit Ill look into adding it. Thank you!

**Comment by mezotv** [comment]
I have just added this in the latest commit!
