### ISSUE TITLE
Little Typing Mistake on Readme: 

### ISSUE THREAD

**Issue by xentzenith** [mezotv/discord-badges#31]
**Describe the bug**
Look for word offical ----> *official

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xentzenith** [comment]
https://github.com/mezotv/discord-badges/pull/32

**Comment by mezotv** [comment]
Please make a proper report with actual information next time, closing this!
